dist: xenial
language: python
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

env:
  global:
    - BUILD_ON_TRAVIS=true

# install dependencies
install:
  - pip install -r requirements.txt

# run tests
script:
  - python bingo/manage.py makemigrations
  - python bingo/manage.py migrate
  - make test

# generate coverage report
after_success:
  - codecov