dist: xenial
language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "3.8"

env:
  global:
    - BUILD_ON_TRAVIS=true

# install dependencies
install:
  - pip install -r requirements.txt

# run tests
script:
  - make test

# generate coverage report
after_success:
  - codecov
